server.port=8082
spring.application.name=sms_service
spring.jpa.defer-datasource-initialization=true

twilio.account.sid=AC17de187ad900d193aed3c301fc2f2355
twilio.auth.token=e26bb23c6cf7ecda64deefdaa88e20b3
twilio.phone.number=+17373093521
twilio.whatsapp.number=whatsapp:+14155238886
